<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sale/_create.blade.php" was generated by ProBot AI.
* Date: 5/29/2023 12:50:43 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Create Sale')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sales.index')}}">Manage</a>
<form action="{{route('sales.store')}}" method ="post" enctype="multipart/form-data">
@csrf
<div class="row mb-3">
	<label for="customer_id" class="col-sm-2 col-form-label">Customer</label>
	<div class="col-sm-10">
		<select class="form-control" name="customer_id" id="customer_id">
			@foreach($customers as $customer)
				<option value="{{$customer->id}}">{{$customer->name}}</option>
			@endforeach
		</select>
	</div>
</div>
<div class="row mb-3">
	<label for="shipping_address" class="col-sm-2 col-form-label">Shipping Address</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="shipping_address" id="shipping_address" placeholder="Shipping Address"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="sales_total" class="col-sm-2 col-form-label">Sales Total</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="sales_total" id="sales_total" placeholder="Sales Total">
	</div>
</div>
<div class="row mb-3">
	<label for="paid_amount" class="col-sm-2 col-form-label">Paid Amount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="paid_amount" id="paid_amount" placeholder="Paid Amount">
	</div>
</div>
<div class="row mb-3">
	<label for="remark" class="col-sm-2 col-form-label">Remark</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="remark" id="remark" placeholder="Remark"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="status" class="col-sm-2 col-form-label">Status</label>
	<div class="col-sm-10">
		<textarea class="form-control" name="status" id="status" placeholder="Status"></textarea>
	</div>
</div>
<div class="row mb-3">
	<label for="discount" class="col-sm-2 col-form-label">Discount</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="discount" id="discount" placeholder="Discount">
	</div>
</div>
<div class="row mb-3">
	<label for="vat" class="col-sm-2 col-form-label">Vat</label>
	<div class="col-sm-10">
		<input type = "text" class="form-control" name="vat" id="vat" placeholder="Vat">
	</div>
</div>

<button type="submit" class="btn btn-primary">Save</button>
</form>
@endsection
@section('script')


@endsection
