<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sale/_index.blade.php" was generated by ProBot AI.
* Date: 5/29/2023 12:50:43 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Manage Sale')
@section('style')


@endsection
@section('page')
<a href="{{route('sales.create')}}">New Sale</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Customer Id</th>
			<th>Sales Date</th>
			<th>Delivery Date</th>
			<th>Shipping Address</th>
			<th>Sales Total</th>
			<th>Paid Amount</th>
			<th>Remark</th>
			<th>Status</th>
			<th>Discount</th>
			<th>Vat</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	@foreach($sales as $sale)
		<tr>
			<td>{{$sale->id}}</td>
			<td>{{$sale->customer_id}}</td>
			<td>{{$sale->sales_date}}</td>
			<td>{{$sale->delivery_date}}</td>
			<td>{{$sale->shipping_address}}</td>
			<td>{{$sale->sales_total}}</td>
			<td>{{$sale->paid_amount}}</td>
			<td>{{$sale->remark}}</td>
			<td>{{$sale->status}}</td>
			<td>{{$sale->discount}}</td>
			<td>{{$sale->vat}}</td>
			<td>{{$sale->created_at}}</td>
			<td>{{$sale->updated_at}}</td>

			<td>
			<form action = "{{route('sales.destroy',$sale->id)}}" method = "post">
				<a class= 'btn btn-primary' href = "{{route('sales.show',$sale->id)}}">View</a>
				<a class= 'btn btn-success' href = "{{route('sales.edit',$sale->id)}}"> Edit </a>
				@method('DELETE')
				@csrf
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	@endforeach
	</tbody>
</table>
@endsection
@section('script')


@endsection
