<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/sale/_show.blade.php" was generated by ProBot AI.
* Date: 5/29/2023 12:50:43 AM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show Sale')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('sales.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$sale->id}}</td></tr>
		<tr><th>Customer Id</th><td>{{$sale->customer_id}}</td></tr>
		<tr><th>Sales Date</th><td>{{$sale->sales_date}}</td></tr>
		<tr><th>Delivery Date</th><td>{{$sale->delivery_date}}</td></tr>
		<tr><th>Shipping Address</th><td>{{$sale->shipping_address}}</td></tr>
		<tr><th>Sales Total</th><td>{{$sale->sales_total}}</td></tr>
		<tr><th>Paid Amount</th><td>{{$sale->paid_amount}}</td></tr>
		<tr><th>Remark</th><td>{{$sale->remark}}</td></tr>
		<tr><th>Status</th><td>{{$sale->status}}</td></tr>
		<tr><th>Discount</th><td>{{$sale->discount}}</td></tr>
		<tr><th>Vat</th><td>{{$sale->vat}}</td></tr>
		<tr><th>Created At</th><td>{{$sale->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$sale->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
