<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/product/_index.blade.php" was generated by ProBot AI.
 * Date: 4/30/2023 2:03:49 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Manage Product')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Manage Products
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success" href="{{ route('products.create') }}">New
                            Product</a>
                    </li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Manage Product</h4>
                    <p class="card-description">
                    </p>
                    <div class="table-responsive">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Name</th>
                                    <th>Offer Price</th>
                                    <th>Manufacturer</th>
                                    <th>Regular Price</th>
                                    <th>Description</th>
                                    <th>Photo</th>
                                    <th>Category</th>
                                    <th>Offer Discount</th>
                                    <th>Uom</th>
                                    <th>Weight</th>
                                    <th>Barcode</th>


                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($products as $product)
                                    <tr>
                                        <td>{{ $product->id }}</td>
                                        <td>{{ $product->name }}</td>
                                        <td>{{ $product->offer_price }}</td>
                                        <td>{{ $product->mfg }}</td>
                                        <td>{{ $product->regular_price }}</td>
                                        <td>{{ $product->description }}</td>
                                        <td><img src="{{ asset('img/' . $product->photo) }}" width="100" /></td>
                                        <td>{{ $product->cat }}</td>
                                        <td>{{ $product->offer_discount }}</td>
                                        <td>{{ $product->uom }}</td>
                                        <td>{{ $product->weight }}</td>
                                        <td>{{ $product->barcode }}</td>


                                        <td>
                                            <form action="{{ route('products.destroy', $product->id) }}" method="post">
                                                <a class='btn btn-primary'
                                                    href="{{ route('products.show', $product->id) }}">View</a>
                                                <a class='btn btn-success'
                                                    href="{{ route('products.edit', $product->id) }}"> Edit </a>
                                                @method('DELETE')
                                                @csrf
                                                <input type="submit" class="btn btn-danger" name="delete" value="Delete" />
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')


@endsection
