<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/product/_show.blade.php" was generated by ProBot AI.
 * Date: 4/30/2023 2:03:49 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Show Product')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Show Product
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class='btn btn-success'
                            href="{{ route('products.index') }}">Manage Product</a>

                    </li>
                </ol>
            </nav>
        </div>

        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Show Product</h4>
                  
                    <table class='table table-striped text-nowrap'>
                        <tbody>
                            <tr>
                                <th>Id</th>
                                <td>{{ $product->id }}</td>
                            </tr>
                            <tr>
                                <th>Name</th>
                                <td>{{ $product->name }}</td>
                            </tr>
                            <tr>
                                <th>Offer Price</th>
                                <td>{{ $product->offer_price }}</td>
                            </tr>
                            <tr>
                                <th>Manufacturer</th>
                                <td>{{ $product->mfg }}</td>
                            </tr>
                            <tr>
                                <th>Regular Price</th>
                                <td>{{ $product->regular_price }}</td>
                            </tr>
                            <tr>
                                <th>Description</th>
                                <td>{{ $product->description }}</td>
                            </tr>
                            <tr>
                                <th>Photo</th>
                                <td><img src="{{ asset('img/' . $product->photo) }}" width="100" /></td>
                            </tr>
                            <tr>
                                <th>Category</th>
                                <td>{{ $product->cat }}</td>
                            </tr>
                            <tr>
                                <th>Is Featured</th>
                                <td>{{ $product->is_featured }}</td>
                            </tr>
                            <tr>
                                <th>Star</th>
                                <td>{{ $product->star }}</td>
                            </tr>
                            <tr>
                                <th>Offer Discount</th>
                                <td>{{ $product->offer_discount }}</td>
                            </tr>
                            <tr>
                                <th>Uom </th>
                                <td>{{ $product->uom}}</td>
                            </tr>
                            <tr>
                                <th>Weight</th>
                                <td>{{ $product->weight }}</td>
                            </tr>
                            <tr>
                                <th>Barcode</th>
                                <td>{{ $product->barcode }}</td>
                            </tr>
                            <tr>
                                <th>Created At</th>
                                <td>{{ $product->created_at }}</td>
                            </tr>
                            <tr>
                                <th>Updated At</th>
                                <td>{{ $product->updated_at }}</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')


@endsection
