<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/stock/_edit.blade.php" was generated by ProBot AI.
 * Date: 5/4/2023 7:02:27 PM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Edit Stock')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Edit Stock
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success"
                            href="{{ url('stocks') }}">Manage Stock</a></li>
                </ol>
            </nav>
        </div>

        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Edit Stock</h4>

                    <form action="{{ url('/stocks') }}/{{ $stock->id }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row mb-3">
                            <label for="product_id" class="col-sm-2 col-form-label">Product</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="product_id" id="product_id">
                                    @foreach ($products as $product)
                                        @if ($product->id == $stock->product_id)
                                            <option value="{{ $product->id }}" selected>{{ $product->name }}</option>
                                        @else
                                            <option value="{{ $product->id }}">{{ $product->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="qty" class="col-sm-2 col-form-label">Qty</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="qty" value="{{ $stock->qty }}"
                                    id="qty"S>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="remark" class="col-sm-2 col-form-label">Remark</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="remark" value="{{ $stock->remark }}"
                                    id="remark">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Save Change</button>
                    </form>
                </div>
            </div>
        </div>
    @endsection
    @section('script')


    @endsection
