<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/stock/_index.blade.php" was generated by ProBot AI.
 * Date: 5/4/2023 7:02:27 PM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Manage Stock')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Manage Stock
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success"
                            href="{{ url('stocks/create') }}">Create Stock</a></li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Manage Stock</h4>

                    <div class="table-responsive">
                        <table class="table table-hover text-nowrap">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Product</th>
                                    <th>Qty</th>
                                    <th>Remark</th>


                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($stocks as $stock)
                                    <tr>
                                        <td>{{ $stock->id }}</td>
                                        <td>{{ $stock->product}}</td>
                                        <td>{{ $stock->qty }}</td>
                                        <td>{{ $stock->remark }}</td>


                                        <td>
                                            <form action="{{ route('stocks.destroy', $stock->id) }}" method="post">
                                                <a class='btn btn-primary'
                                                    href="{{ route('stocks.show', $stock->id) }}">View</a>
                                                <a class='btn btn-success' href="{{ route('stocks.edit', $stock->id) }}">
                                                    Edit </a>
                                                @method('DELETE')
                                                @csrf
                                                <input type="submit" class="btn btn-danger" name="delete"
                                                    value="Delete" />
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')


@endsection
