<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/purchase/_show.blade.php" was generated by ProBot AI.
 * Date: 5/6/2023 1:47:57 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Details Purchase')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Details Purchase
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success"
                            href="{{ url('purchases') }}">Manage Purchase</a></li>
                </ol>
            </nav>
        </div>
        <div class="card">
            <div class="card-body">
                <div class="row">
                    <div class="col-12">
                        <div class="table-responsive">
                            <table class='table table-striped text-nowrap'>
                                <tbody>
                                    <tr>
                                        <th>Id</th>
                                        <td>{{ $purchase->id }}</td>
                                    </tr>
                                    <tr>
                                        <th>Name</th>
                                        <td>{{ $purchase->pdt }}</td>
                                    </tr>
                                    <tr>
                                        <th>Supplier </th>
                                        <td>{{ $purchase->spl }}</td>
                                    </tr>
                                    <tr>
                                        <th>Purchase Date</th>
                                        <td>{{ $purchase->purchase_date }}</td>
                                    </tr>
                                    <tr>
                                        <th>Delivery Date</th>
                                        <td>{{ $purchase->delivery_date }}</td>
                                    </tr>
                                    <tr>
                                        <th>Shipping Address</th>
                                        <td>{{ $purchase->shipping_address }}</td>
                                    </tr>
                                    <tr>
                                        <th>Purchase Total</th>
                                        <td>{{ $purchase->purchase_total }}</td>
                                    </tr>
                                    <tr>
                                        <th>Paid Amount</th>
                                        <td>{{ $purchase->paid_amount }}</td>
                                    </tr>
                                    <tr>
                                        <th>Remark</th>
                                        <td>{{ $purchase->remark }}</td>
                                    </tr>
                                    <tr>
                                        <th>Discount</th>
                                        <td>{{ $purchase->discount }}</td>
                                    </tr>
                                    <tr>
                                        <th>Vat</th>
                                        <td>{{ $purchase->vat }}</td>
                                    </tr>
                                    <tr>
                                        <th>Created At</th>
                                        <td>{{ $purchase->created_at }}</td>
                                    </tr>
                                    <tr>
                                        <th>Updated At</th>
                                        <td>{{ $purchase->updated_at }}</td>
                                    </tr>

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')


@endsection
