<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/purchase/_edit.blade.php" was generated by ProBot AI.
 * Date: 5/6/2023 1:47:57 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Edit Purchase')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Edit Purchase
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success"
                            href="{{ url('purchases') }}">Manage Purchase</a></li>
                </ol>
            </nav>
        </div>

        <div class="col-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <form action="{{ url('/purchases') }}/{{ $uom->id }}" method="post" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        <div class="row mb-3">
                            <label for="name" class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name" value="{{ $purchase->name }}"
                                    id="name" placeholder="Name">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="supplier_id" class="col-sm-2 col-form-label">Supplier</label>
                            <div class="col-sm-10">
                                <select class="form-control" name="supplier_id" id="supplier_id">
                                    @foreach ($suppliers as $supplier)
                                        @if ($supplier->id == $purchase->supplier_id)
                                            <option value="{{ $supplier->id }}" selected>{{ $supplier->name }}</option>
                                        @else
                                            <option value="{{ $supplier->id }}">{{ $supplier->name }}</option>
                                        @endif
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="shipping_address" class="col-sm-2 col-form-label">Shipping Address</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="shipping_address"
                                    value="{{ $purchase->shipping_address }}" id="shipping_address"
                                    placeholder="Shipping Address">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="purchase_total" class="col-sm-2 col-form-label">Purchase Total</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="purchase_total"
                                    value="{{ $purchase->purchase_total }}" id="purchase_total"
                                    placeholder="Purchase Total">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="paid_amount" class="col-sm-2 col-form-label">Paid Amount</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="paid_amount"
                                    value="{{ $purchase->paid_amount }}" id="paid_amount" placeholder="Paid Amount">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="remark" class="col-sm-2 col-form-label">Remark</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="remark" value="{{ $purchase->remark }}"
                                    id="remark" placeholder="Remark">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="discount" class="col-sm-2 col-form-label">Discount</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="discount" value="{{ $purchase->discount }}"
                                    id="discount" placeholder="Discount">
                            </div>
                        </div>
                        <div class="row mb-3">
                            <label for="vat" class="col-sm-2 col-form-label">Vat</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="vat" value="{{ $purchase->vat }}"
                                    id="vat" placeholder="Vat">
                            </div>
                        </div>

                        <button type="submit" class="btn btn-primary">Save Change</button>
                    </form>
                </div>
            </div>
        </div>
    @endsection
    @section('script')


    @endsection
