<?php
/*
 * ProBot Version: 3.0
 * Laravel Version: 10x
 * Description: This source file "resources/views/category/_index.blade.php" was generated by ProBot AI.
 * Date: 5/4/2023 4:11:43 AM
 * Contact: towhid1@outlook.com
 */
?>
@extends('layout.erp.app')
@section('title', 'Manage Category')
@section('style')


@endsection
@section('page')
    <div class="content-wrapper">
        <div class="page-header">
            <h3 class="page-title">
                Manage Category
            </h3>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a class="btn btn-info" href="{{ url('dashboard') }}">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page"><a class="btn btn-success"
                            href="{{ url('categories/create') }}">Create Category</a></li>
                </ol>
            </nav>
        </div>
        <div class="col-lg-12 stretch-card">
            <div class="card">
                <div class="card-body">
                    <table class="table table-hover text-nowrap">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Name</th>
                              
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($categorys as $category)
                                <tr>
                                    <td>{{ $category->id }}</td>
                                    <td>{{ $category->name }}</td>
                                    

                                    <td>
                                        <form action="{{ route('categories.destroy', $category->id) }}" method="post">
                                            <a class='btn btn-primary'
                                                href="{{ route('categories.show', $category->id) }}">View</a>
                                            <a class='btn btn-success' href="{{ route('categories.edit', $category->id) }}">
                                                Edit </a>
                                            @method('DELETE')
                                            @csrf
                                            <input type="submit" class="btn btn-danger" name="delete" value="Delete" />
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')


@endsection
