<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ProductController.php" was generated by ProBot AI.
* Date: 4/30/2023 2:06:34 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\Category;
use App\Models\Uom;
use App\Models\Manufacturer;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ProductController extends Controller{
	public function index(){

		

		$products =DB::table('products as p')
		->join('manufacturers as m','p.manufacturer_id','=','m.id')
		->join('categories as c','p.category_id','=','c.id')
		->join('uoms as u','p.uom_id','=','u.id')
		->select('p.id','p.name','p.offer_price','m.name as mfg','p.regular_price','p.description','p.photo','c.name as cat',
		'p.is_featured','p.star','p.offer_discount','u.name as uom','p.weight','p.barcode','p.created_at','p.updated_at')
		->paginate(10);
		return view("pages.erp.product.index",["products"=>$products]);
		
	}
	public function create(){
		return view("pages.erp.product.create",["categories"=>Category::all(),"uoms"=>Uom::all(),"manufacturers"=>Manufacturer::all()]);
	}
	public function store(Request $request){
		//Product::create($request->all());
		$product = new Product;
		$product->name=$request->name;
		$product->offer_price=$request->offer_price;
		$product->manufacturer_id=$request->manufacturer_id;
		$product->regular_price=$request->regular_price;
		$product->description=$request->description;
		if(isset($request->photo)){
			$product->photo=$request->photo;
		}
		$product->category_id=$request->category_id;
		$product->is_featured=$request->is_featured;
		$product->star=$request->star;
		$product->offer_discount=$request->offer_discount;
		$product->uom_id=$request->uom_id;
		$product->weight=$request->weight;
		$product->barcode=$request->barcode;
date_default_timezone_set("Asia/Dhaka");
		$product->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$product->updated_at=date('Y-m-d H:i:s');

		$product->save();
		if(isset($request->photo)){
			$imageName=$product->id.'.'.$request->photo->extension();
			$product->photo=$imageName;
			$product->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$product = DB::table('products as p')
		->join('manufacturers as m','p.manufacturer_id','=','m.id')
		->join('categories as c','p.category_id','=','c.id')
		->join('uoms as u','p.uom_id','=','u.id')
		->where('p.id',$id)
		->select('p.id','p.name','p.offer_price','m.name as mfg','p.regular_price','p.description','p.photo','c.name as cat','p.is_featured','p.star','p.offer_discount','u.name as uom','p.weight','p.barcode','p.created_at','p.updated_at')
		->first();
		return view("pages.erp.product.show",["product"=>$product]);

	}
	public function edit(Product $product){
		return view("pages.erp.product.edit",["product"=>$product,"categories"=>Category::all(),"uom"=>Uom::all()]);
	}
	public function update(Request $request,Product $product){
		//Product::update($request->all());
		$product = Product::find($product->id);
		$product->name=$request->name;
		$product->offer_price=$request->offer_price;
		$product->manufacturer_id=$request->manufacturer_id;
		$product->regular_price=$request->regular_price;
		$product->description=$request->description;
		if(isset($request->photo)){
			$product->photo=$request->photo;
		}
		$product->category_id=$request->category_id;
		$product->is_featured=$request->is_featured;
		$product->star=$request->star;
		$product->offer_discount=$request->offer_discount;
		$product->uom_id=$request->uom_id;
		$product->weight=$request->weight;
		$product->barcode=$request->barcode;
date_default_timezone_set("Asia/Dhaka");
		$product->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$product->updated_at=date('Y-m-d H:i:s');

		$product->save();
		if(isset($request->photo)){
			$imageName=$product->id.'.'.$request->photo->extension();
			$product->photo=$imageName;
			$product->update();
			$request->photo->move(public_path('img'),$imageName);
		}

		return redirect()->route("products.index")->with('success','Updated Successfully.');
	}
	public function destroy(Product $product){
		$product->delete();
		return redirect()->route("products.index")->with('success', 'Deleted Successfully.');
	}
}
?>
