<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PurchaseDetailController.php" was generated by ProBot AI.
* Date: 5/8/2023 12:08:35 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Purchase_Detail;
use App\Models\Purchase;

use App\Models\Product;
use App\Models\Uom;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PurchaseDetailController extends Controller{
	public function index(){
		$purchasedetails = Purchase_Detail::paginate(10);
		return view("pages.erp.purchasedetail.index",["purchasedetails"=>$purchasedetails]);
	}
	public function create(){
		return view("pages.erp.purchasedetail.create",["purchases"=>Purchase::all(),"products"=>Product::all(),"uom"=>Uom::all()]);
	}
	public function store(Request $request){
		//PurchaseDetail::create($request->all());
		$purchasedetail = new Purchase_Detail;
		$purchasedetail->purchase_id=$request->purchase_id;
		$purchasedetail->product_id=$request->product_id;
		$purchasedetail->uom_id=$request->uom_id;
		$purchasedetail->price=$request->price;
		$purchasedetail->vat=$request->vat;
		$purchasedetail->discount=$request->discount;
date_default_timezone_set("Asia/Dhaka");
		$purchasedetail->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$purchasedetail->updated_at=date('Y-m-d H:i:s');

		$purchasedetail->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$purchasedetail = Purchase_Detail::find($id);
		return view("pages.erp.purchasedetail.show",["purchasedetail"=>$purchasedetail]);
	}
	public function edit(Purchase_Detail $purchasedetail){
		return view("pages.erp.purchasedetail.edit",["purchasedetail"=>$purchasedetail,"purchases"=>Purchase::all(),"products"=>Product::all(),"uom"=>Uom::all()]);
	}
	public function update(Request $request,Purchase_Detail $purchasedetail){
		//PurchaseDetail::update($request->all());
		$purchasedetail = Purchase_Detail::find($purchasedetail->id);
		$purchasedetail->purchase_id=$request->purchase_id;
		$purchasedetail->product_id=$request->product_id;
		$purchasedetail->uom_id=$request->uom_id;
		$purchasedetail->price=$request->price;
		$purchasedetail->vat=$request->vat;
		$purchasedetail->discount=$request->discount;
date_default_timezone_set("Asia/Dhaka");
		$purchasedetail->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$purchasedetail->updated_at=date('Y-m-d H:i:s');

		$purchasedetail->save();

		return redirect()->route("purchasedetails.index")->with('success','Updated Successfully.');
	}
	public function destroy(Purchase_Detail $purchasedetail){
		$purchasedetail->delete();
		return redirect()->route("purchasedetails.index")->with('success', 'Deleted Successfully.');
	}
}
?>
