<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SaleController.php" was generated by ProBot AI.
* Date: 5/28/2023 2:43:53 AM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Sale;
use App\Models\Customer;
use App\Models\Product;


use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SaleController extends Controller{
	public function index(){
		$sales = Sale::paginate(10);
		return view("pages.erp.sale.index",["sales"=>$sales]);
	}
	public function create(){
		return view("pages.erp.sale.createsales",["customers"=>Customer::all(),"products"=>Product::all()]);
	}
	public function store(Request $request){
		//Sale::create($request->all());
		$sale = new Sale;
		$sale->customer_id=$request->customer_id;
		$sale->sales_date=$request->sales_date;
		$sale->delivery_date=$request->delivery_date;
		$sale->shipping_address=$request->shipping_address;
		$sale->sales_total=$request->sales_total;
		$sale->paid_amount=$request->paid_amount;
		$sale->remark=$request->remark;
		$sale->status=$request->status;
		$sale->discount=$request->discount;
		$sale->vat=$request->vat;
date_default_timezone_set("Asia/Dhaka");
		$sale->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$sale->updated_at=date('Y-m-d H:i:s');

		$sale->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$sale = Sale::find($id);
		return view("pages.erp.sale.show",["sale"=>$sale]);
	}
	public function edit(Sale $sale){
		return view("pages.erp.sale.edit",["sale"=>$sale,"customers"=>Customer::all()]);
	}
	public function update(Request $request,Sale $sale){
		//Sale::update($request->all());
		$sale = Sale::find($sale->id);
		$sale->customer_id=$request->customer_id;
		$sale->sales_date=$request->sales_date;
		$sale->delivery_date=$request->delivery_date;
		$sale->shipping_address=$request->shipping_address;
		$sale->sales_total=$request->sales_total;
		$sale->paid_amount=$request->paid_amount;
		$sale->remark=$request->remark;
		$sale->status=$request->status;
		$sale->discount=$request->discount;
		$sale->vat=$request->vat;
date_default_timezone_set("Asia/Dhaka");
		$sale->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$sale->updated_at=date('Y-m-d H:i:s');

		$sale->save();

		return redirect()->route("sales.index")->with('success','Updated Successfully.');
	}
	public function destroy(Sale $sale){
		$sale->delete();
		return redirect()->route("sales.index")->with('success', 'Deleted Successfully.');
	}
}
?>
