<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_SupplierController.php" was generated by ProBot AI.
* Date: 5/4/2023 6:15:45 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Supplier;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class SupplierController extends Controller{
	public function index(){
		$suppliers = Supplier::paginate(10);
		return view("pages.erp.supplier.managesupplier",["suppliers"=>$suppliers]);
	}
	public function create(){
		return view("pages.erp.supplier.createsupplier",[]);
	}
	public function store(Request $request){
		//Supplier::create($request->all());
		$supplier = new Supplier;
		$supplier->name=$request->name;
		$supplier->mobile=$request->mobile;
		$supplier->email=$request->email;
		$supplier->address=$request->address;
date_default_timezone_set("Asia/Dhaka");
		$supplier->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$supplier->updated_at=date('Y-m-d H:i:s');

		$supplier->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$supplier = Supplier::find($id);
		return view("pages.erp.supplier.detailssupplier",["supplier"=>$supplier]);
	}
	public function edit(Supplier $supplier){
		return view("pages.erp.supplier.editsupplier",["supplier"=>$supplier,]);
	}
	public function update(Request $request,Supplier $supplier){
		//Supplier::update($request->all());
		$supplier = Supplier::find($supplier->id);
		$supplier->name=$request->name;
		$supplier->mobile=$request->mobile;
		$supplier->email=$request->email;
		$supplier->address=$request->address;
date_default_timezone_set("Asia/Dhaka");
		$supplier->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$supplier->updated_at=date('Y-m-d H:i:s');

		$supplier->save();

		return redirect()->route("suppliers.index")->with('success','Updated Successfully.');
	}
	public function destroy(Supplier $supplier){
		$supplier->delete();
		return redirect()->route("suppliers.index")->with('success', 'Deleted Successfully.');
	}
}
?>
